package utils

const (
	// POSTGRESHOST :
	POSTGRESHOST = "POSTGRES_HOST"
	// POSTGRESPORT :
	POSTGRESPORT = "POSTGRES_PORT"
	// POSTGRESUSER :
	POSTGRESUSER = "POSTGRES_USER"
	// POSTGRESPASSWORD :
	POSTGRESPASSWORD = "POSTGRES_PASSWORD"
	// POSTGRESDATABASE :
	POSTGRESDATABASE = "POSTGRES_DATABASE"

	// PORT :
	PORT = "PORT"

	// EmptyString :
	EmptyString = ""
)
